# Generated by Django 4.2.7 on 2023-11-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(help_text='Class Name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Name', models.CharField(help_text='School Name', max_length=50)),
                ('School_Address', models.CharField(help_text='School Address', max_length=100)),
                ('School_Telephone', models.CharField(help_text='Telephone', max_length=20)),
                ('School_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_firstName', models.CharField(help_text='Teacher First Name', max_length=20)),
                ('teacher_lastName', models.CharField(help_text='Teacher Last Name', max_length=20)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('extension', models.CharField(choices=[('mr', 'Mr.'), ('ms', 'Ms.'), ('miss', 'Miss')], max_length=10)),
                ('classID', models.ManyToManyField(to='school.classname')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_First_Name', models.CharField(help_text='First Name', max_length=20)),
                ('Student_Last_Name', models.CharField(help_text='Last Name', max_length=20)),
                ('student_dateOfBirth', models.DateField()),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('classID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.classname')),
                ('schoolID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.AddField(
            model_name='classname',
            name='schoolID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
